---
title: "Covid-19: How Can Sports Come Back?"
date: "4/17/2020"
---

**Updated 5/27/2020 at 9:30am ET**

I've been giving a lot of interviews lately on the effects of Covid-19 on professional, college, and youth sports. Lately many of these have focused on some natural questions for folks to have: When and how can sports come back?

These are really difficult questions, but I'm doing my best to give realistic answers that help people set reasonable expectations. I often focus on various aspects of the problem in different interviews, so I wanted to collect all my thoughts here in one place.

Before we get started, you all should know that I am *not* an infectious disease expert, a virologist, or an immunologist. I'm a PhD-level epidemiologist, but I focus on sports issues. My goal is to serve to bridge the gap between public health and sports. I talk extensively with my infectious disease colleagues to try and make sure everything I'm saying is accurate, but you should take their word over mine should we ever disagree (and if I discover we do, I'll update this post to their views ASAP).

OK, here we go.

## My overarching message to sports fans right now, in case you plan to stop reading soon.

The more aggressively we act to beat back Covid-19 now the sooner we can have sports back. For whatsoever a man soweth, that shall he also reap (Galatians 6:7). We can only reap the benefits of having a low number of cases of Covid-19 cases floating around -- such as being able to move back towards normality -- if we do the work needed to get there. If we skip over the needed work we will pay a very steep cost.

Furthermore, the harder we work to keep Covid-19 contained once we get sports back -- such as with aggressive and widespread testing to quickly identify new cases, isolate them, and trace and quarantine their contacts -- the less likely we are to lose them again due to an explosion in new cases. If we don't keep the pressure on we [risk losing any progress we make in the meantime](https://www.nytimes.com/2020/04/28/sports/fauci-sports-reopening-pandemic.html?auth=login-google&smid=tw-nytsports&smtyp=cur) -- backsliding to a time like early April when the return of sports seemed unthinkable.

Do you want sports back? Great, me too. Believe me, there is not an epidemiologist out there who wants sports (especially football) back more than I do. So work with me and listen when I tell you to listen to my infectious disease colleagues and your local public health authorities, because the things they're telling you to do are the things that will put us on the road back to normality the quickest without allowing mass death.

It's like aggressively tanking to get a whole bunch of draft picks to improve the team versus being just sort of mediocre for years on end. To put things in the most insufferable sports terms possible: Trust the Process.

We *should* still be in the Teardown in many areas right now -- it's deeply painful and unpleasant but necessary to get where we want to be, but the more aggressively we do it the less time we spend in it. The Teardown involves socially distancing to slow the disease's spread (done-ish) and get the number of new cases down to a point where we can handle them through other less draconian means (not at all done).

Then we can move into the Rebuild, where things start improving little by little and we start to see the light at the end of the tunnel. Leadership in many areas of the U.S. (though notably not a majority of people in polls) and the federal government seem content to try and force us into the Rebuild now. Many experts (myself included) fear most areas should still be in the Teardown, and if we're right a decision to try and start the Rebuild now could be disastrous. The Rebuild requires the capacity to test a lot of people repeatedly, quickly identify and isolate new cases, and trace and quarantine their contacts before small outbreaks can get beyond our limits to control without shuttering businesses and sheltering in place.

Then, finally, our goal is a Championship -- a vaccine, but that's late 2021 at best. And we can't get there without the Teardown and Rebuild. Teardown, Rebuild, Championship. We could get there together.

We all have to work together. We're teammates right now, like it or not. Let's all stop freelancing, listen to our coaches, and start pulling in the same direction.

## Alright coach, start me with the bad news. Sports with fans. When can we be cheering in packed stadiums again?

It's very likely we won't have sports with fans back until we have a Covid-19 vaccine mass-administered, which is most likely going to be at least late 2021.

The key thing to understand is that every person you add to a gathering increases the risk of Covid-19 in two ways: it's another person who could be bringing the infection in; or, even if they're uninfected, they're another person who could catch the disease from someone else and spread it to others. The safest you can be is one person alone in a house or apartment because no one can bring the disease to you in that situation, and you can't get anyone else sick. Two people is more dangerous than one, ten is more dangerous than two, 500 is more dangerous than ten. By the time you get up to 50,000, 70,000, 100,000 fans the danger level really ratchets up. These are the types of situations where you run the risk of having a super-spreading event where a whole lot of people get sick at once and overwhelm the local public health and, eventually, medical systems. If fans are coming in from out of town -- for example, for a World Series game -- this single sporting event could also seed new outbreaks in areas all across the country that had otherwise been doing a good job containing the epidemic.

To be clear, this doesn't just apply to sports. It's unlikely we'll be able to gather safely in the thousands for anything -- festivals, conventions, sporting events -- until we have a vaccine.

Although Dr. Fauci has [noted the possibility of events with fans this year](https://twitter.com/arthomason/status/1263974830451372037?s=20) I think it's important to note he says this is possible when there is "very, very little infection in a community." What does very, very little mean? I can't speak for Dr. Fauci, but to me it means a situation like Taiwan -- single digit numbers of new cases in a population over 20 million. Most areas of the U.S. aren't anywhere close to that, nor do I see them being so any time this year given our late and weak response compared to Taiwan, South Korea, New Zealand, and even Germany. Sure Montana, Alaska, and Hawaii are, but they have a grand total of zero Big 4 pro sports teams, and I don't hear anyone suggesting relocating leagues there for logistical reasons.

## What about stadiums only filling to a fraction of their capacity?

Some people have floated the idea of having fans at games but keeping stadiums at, say, 15-20% capacity so they can keep fans 6 feet apart in the stands. I'm extremely skeptical. How do you keep people apart during entry? Exit? Concessions and beer lines? Bathrooms? Do you really think every fan is going to arrive at their appointed time or, even harder, sit around and leave at the exact assigned time for their row (especially after an emotional ending, positive or negative)?

It's also important to remember that the "6 foot rule" is really a loose guideline. It's not like if you're 5'11" away from someone you're going to catch any infection and if you're 6'1″ away you're 100% safe. It's a continuum where the further away you are the safer you are. It's also highly context-dependent. We know things like [yelling and singing](https://www.nytimes.com/2020/05/12/health/coronavirus-choir.html) (you've never done either of those at a sports event, have you!?) project respiratory droplets farther and increase the risk of Covid-19 transmission. So it doesn't really make sense to tell people "stay 6 feet away from other people at the grocery store, and also in a raucous stadium." Maybe people would actually need to be spaced out by 20 feet in a stadium to keep risk low. We don't know exactly, but my point in bringing this up is to note it's a lot more complicated than most people are saying.

Some people and media outlets have interpreted this as me saying all sports are doomed, period, until we have a vaccine. Not so.

## So what about sports without fans?

[**We can likely bring sports without fans back substantially earlier simply because that involves far fewer people and thus reduces risks substantially.**]{.underline} I don't want to make a time-based forecast because that's not the way we should be thinking. It's not "oh, if we just socially distance for another month we'll be back where we need to be and can play sports again." [**What will determine when we get sports back are conditions on the ground, not time passing.**]{.underline}

By conditions on the ground I basically mean the number of active cases. If we can slow new cases to a trickle and have few active cases floating around the population with very little community-based person-to-person transmission, that makes it somewhat safer to gather in large numbers. The lower the number of active cases, the larger gatherings we can have at the same level of risk. Because different sports require different numbers of people to pull off there is no single level where we can say "OK, it's low enough that sports can come back." Different leagues may also have different plans for returning that each necessitate different conditions to be done safely -- more on that below. It's all a continuum. My overarching message would be to [**listen to epidemiologists, infectious disease experts, and local public health officials.**]{.underline} Only resume any form of sports if they sign off on your particular plan.

We also need to have enough Covid-19 diagnostic tests for leagues to aggressively test their athletes, coaches, and support staff, without taking them away from sick people and healthcare workers, or from surveillance programs that need them to support the efforts to identify and isolate cases that are critical to loosening lockdowns more broadly. We also need to be able to divert the medical personnel needed to run an event or season without putting the rest of our healthcare system at risk of being overwhelmed. Diverting tests or medical personnel who are needed to combat the epidemic to support pro sports instead raises serious ethical questions. Unfortunately as of the second week of May [testing growth in the U.S. has been slower than hoped](https://www.theatlantic.com/technology/archive/2020/04/us-coronavirus-outbreak-out-control-test-positivity-rate/610132/) but is now [around 400K daily tests](https://covidtracking.com/data/national) -- [a level still well below what's currently](https://www.nytimes.com/interactive/2020/04/17/us/coronavirus-testing-states.html) [needed in most areas](https://www.statnews.com/2020/04/27/coronavirus-many-states-short-of-testing-levels-needed-for-safe-reopening/).

Dr. Anthony Fauci, the top infectious disease official in the U.S., echoed these same thoughts around case levels and sufficient testing in [a New York Times interview](https://www.nytimes.com/2020/04/28/sports/fauci-sports-reopening-pandemic.html?auth=login-google&smid=tw-nytsports&smtyp=cur) where he also noted that if we can't meet the conditions necessary to guarantee player and public safety then some leagues may not be able to restart at all this season, even without fans.

In more injurious sports we also need to make sure hospitals aren't hotbeds of Covid-19 activity that would either put athletes needing medical attention at high-risk of getting sick or so near to being overwhelmed that athlete injuries would cause undue stress.

Considering all these criteria: we aren't where I'd like us to be yet to even bring fan-free sports back in the U.S. ...but I also don't know that, with states loosening their restrictions and [plateauing or rising cases in many areas of the country](https://www.nytimes.com/interactive/2021/us/covid-cases.html#states) outside of the northeast, we will be any time soon. Tests will continue to rise and hopefully be close to what some experts say we need (0.9-1 million/day) in the next month or two. But it's difficult to ask teams and leagues to wait much more than that when we don't appear to have a nationwide plan to crush case numbers and are content to just keep things where they are, at best. At this point it probably makes sense to be developing plans to bring pro sports back with intense safety restrictions -- more than would be required in many other countries that actually brought the virus under control -- in the next couple months, barring a new nationwide explosion in cases.

## What are the different options for bringing fanless sports back?

Quite a few plans have been issued by leagues in two basic strains. One strain revolves around various degrees of sequestering athletes and other league and support staff in a lower-risk area that both keeps the league safe from the virus circulating in the general population and helps prevent any case that *does* get in to a league's protected zone from getting out and sparking a massive spread in the general population. There is a whole continuum of options here, though, with hundreds of choices and customizations you could make to a plan. Each choice has a risk-benefit tradeoff -- each thing you do to try and control infection risk has an economic, logistical, and/or psychological cost. Each league will have to settle on what level of risk vs. expense they can tolerate. The most strict and safe of these **sequestering plans** would be a true "Biodome" approach.

There is also a second path that revolves around daily Covid-19 testing; I'll call these **testing plans**.

Either strain also involves ramped-up hygiene and physical distancing protocols where possible to limit the potential for any infections to spread.

From either of these ideal plans, you can get into progressively riskier plans that rely on a "softer" sequestering of league and support personnel and/or less frequent testing.

## Let's start with the ideal sequestering plan: a Biodome.

Okay, buuuuuuuuuu-dy. It's a fine place to start. What would a true strict Biodome approach look like?

Everyone critical to the conduct of the sport -- athletes, coaches, officials, medical and training staff, key broadcast staff, and others -- would have to undergo [a period of individual quarantine and Covid-19 testing to ensure they are uninfected **before** entering the protected virus-free zone]{.underline} (not an actual bubble) we'll call the Biodome. The "Biodome" would basically be a geographically-clustered area of living quarters, training facilities, and competition areas. Each person would need to be separately quarantined and then initially tested after 5-7 days to give the virus a chance to rear its head in a positive test, then tested again after a full 14 days to ensure they are still negative and will not develop the virus. This quarantine will have to be much stricter than a stay-at-home order and would ideally be done outside of but as close to the protected virus-free zone as possible. The individual and any family they have chosen to quarantine with would have to find somewhere to live, stay there, and avoid *all* outside human contact with the possible exception of the people administering the Covid-19 tests for two weeks; all deliveries would have to be disinfected. They would then need to be transmitted as quickly and sterilely as possible -- such as via a deep-cleaned bus or van with a driver who has been through quarantine and been living in the virus-free zone or who has a high level of Covid-19 antibodies -- into the protected virus-free zone. All the support staff -- housekeepers and food preparation staff if the league is being housed at hotels, security, bus drivers to transport players from living quarters to training facilities and playing areas -- would have to undergo the same process and live alongside the players and other league personnel in the virus-free zone, spending weeks or months away from their families.

So just getting someone safely into the Biodome is a multi-week process. It's not as easy as you show up, get tested, are negative, and get let in. Even setting aside the issue of false negatives from poor tests or collection procedures, it can take several days for a newly-seeded infection to return a positive test -- in other words, it's possible a player who tested negative and was let into the protected virus-free zone would later turn out to be infected, and the system is compromised. Temperature scans are even worse as we know many cases are asymptomatic and even some with symptoms don't show a high fever.

Once everyone is in the zone you have to maintain a strict closed loop. If families aren't housed in the zone this means everyone from athletes to housekeepers is spending weeks or months away from them. Nobody, not even hotel support staff, enters without going through the strict two-week quarantine and clearance process. Strict security is maintained to stop anybody from sneaking out and returning. If somebody does need to leave, such as to treat an injury or see the birth of their child or visit a dying relative, they have to go through the quarantine and entry process again. All deliveries are disinfected. You should also probably still test regularly to catch any infections that somehow snuck in early...but if you do find one the system is already blown up, frankly.

Most leagues looking at centralization and sequestering aren't going full Biodome. Rather they're going for a softer approach that relaxes some of these guidelines but is still based around centralization and sequestering along with frequent testing. The [closest to a full Biodome I've seen so far is MLS](https://theathletic.com/1829962/2020/05/21/testing-plans-travel-parties-for-mls-orlando-plan-outlined-in-internal-document/).

## The Biodome sounds impossible.

I would say exceedingly difficult, but not theoretically impossible? The big risk is that if even one case *does* get in -- a single lapse by any of the hundreds of people involved -- the whole system is essentially blown up. All the work you put in to set a clean zone is rendered worthless and you're set back at least several weeks. It's a big weak point.

## What about the ideal testing plan?

This plan is quite simple and comes from [Dr. Carl Bergstrom at the University of Washington](https://twitter.com/CT_Bergstrom). It involves testing each and every player, coach, trainer, and support staff -- anyone with any contact with anyone in the league, including people like hotel housekeepers -- for Covid-19 *every day*. The idea would be to catch cases either before or shortly after they become contagious so they only have a low chance of spreading it to anyone else in the league before they can be identified and isolated.

The big benefit of this approach is it eliminates the need to set up a truly closed system with pre-entry quarantines and total sequestering of league staff -- you're essentially saying "OK, we know we're going to have cases just from people's daily lives, but we're going to identify them *so fast* they won't have a chance to cause an explosive outbreak." With this plan hygiene and physical distancing protocols -- such as minimizing team-wide gatherings and relying on practices between consistent small groups of players -- also take on a bigger importance as another layer of security to stop spread.

The big drawback is that this requires a whole lot of tests, which can't take away from society's broader capacity. If teams make the investment to actually ramp up new testing capacity rather than cannibalizing what currently exists -- possibly even building their own labs -- they could [donate more tests than they use](https://www.irishtimes.com/sport/soccer/english-soccer/serie-a-clubs-to-donate-five-test-kits-for-every-one-they-use-1.4238230) to the surrounding community, minimizing ethical concerns. In the U.S., though, we're still not to the point we need to be with testing to accomplish this, and it's not clear when we will be (or why we're not there yet).

The other risk is that it relies on something that's unclear: the time between when you get infected with Covid-19, when you're contagious to others, and when you test positive. If there's a substantial period (say a couple days) between when you become contagious and when you test positive, this plan crumbles. Infectious disease experts like Bergstrom don't think this is likely, however.

Some may argue this plan is independent of the number of active cases in the surrounding area, but I disagree. Even if you're testing everyone every day, more active cases in the population means a higher chance of players or support staff testing positive and needing to be isolated. That's disruptive to team operations, and if even one of them sparks a transmission chain the team could be forced to shut down for several weeks. So reducing the number of cases in the area(s) where you operate -- or relocating to an area with very few active cases, and which you suspect will continue to stay that way -- is still a goal even under this plan.

This plan may also be made easier by advances in testing technology, such as saliva tests (where you can spit in a cup rather than having a long Q-tip tickle your brain) or [antigen tests](https://www.fda.gov/news-events/press-announcements/coronavirus-covid-19-update-fda-authorizes-first-antigen-test-help-rapid-detection-virus-causes) (which are quicker and cheaper, but also less sensitive than, current diagnostic tests that rely on growing and detecting copies of the virus's genetic material).

So far the [Spanish La Liga seems to be the closest](https://www.si.com/soccer/2020/05/11/la-liga-plan-resume-season-coronavirus-positive-tests-spain) to actually executing this plan. They are testing all players, coaches, and other staff involved in individual training sessions each day. They have had 8/2,500 tests turn up positive and immediately isolated those athletes and staffers. It will be very instructive to see if further cases appear on the teams where the positive tests were detected; if not, it could be a good sign for the feasibility of this plan.

## Under the ideal testing plan could teams play in their home markets?

Playing in home markets adds two dimensions of risk. First, you're at the mercy of local conditions -- if even one of 25-30 markets suffers an explosive outbreak one or more teams could lose their ability to practice and play games, which could cause a destructive schedule disruption. To maintain competitive parity your infection control procedures would have to be constantly adapted to the strictest measures of any jurisdiction a team plays or practices in. Some areas may either never allow games to start or abruptly roll that ability back if cases spike; you need a plan for these scenarios. Second, travel, even private charter travel, brings teams in contact -- sometimes close prolonged contact, such as on an airplane -- with more people who have to be subject to any infection control procedures the league adapts. There's also the risk that teams from areas with a lot of cases could bring Covid-19 to markets that had otherwise done a good job of controlling the virus. That would be a public health nightmare. Some areas might even institute travel bans from some especially hot areas with very short notice, causing further scheduling difficulties. Imagine there's an outbreak in Cincinnati and suddenly Illinois Governor Pritzker says the Reds couldn't travel to play the Cubs or White Sox that weekend.

Some sort of centralization -- to one or a few locations based on divisions or conferences -- would reduce these problems substantially. Under the ideal testing plan, "move the family to Vegas for 4-5 months" is probably an easier sell than "leave your family and isolate in a Biodome in Vegas for 4-5 months." If you have multiple locations ("hubs") you should rejigger the travel schedule to minimize travel between the hubs -- ideally just one trip between hubs for each team.

## Are there any easier solutions?

Sure. You can always opt for a "softer" approach that loosens any of the "ideal" protocols for the sequestering or testing plans, but that adds extra risk that may or may not be acceptable based on surrounding conditions. You could ignore the pre-Biodome quarantine and clearance process, for example, or sequester league staff but allow hotel staff to stay home with their families. This appears to be [similar to what Dr. Anthony Fauci is suggesting](https://www.espn.com/espn/story/_/id/29038491/dr-anthony-fauci-promotes-single-site-fan-free-return-sports) for an MLB season later this year; the fact that he foresees conditions allowing this in the coming months should make us all feel more optimistic. Or you could test every two days rather than every day. But these all increase the risk of an explosive Covid-19 outbreak in your league.

"Softer" plans are easier to justify if you are in an area with lower transmission and fewer active cases. It's simple math -- the risk of an infection in your league is higher if 1% of the nearby community is walking around sick than if 0.01% is. [**So to maintain the same level of risk in an area with greater transmission you need to take stricter infection prevention steps.**]{.underline} Taiwan has opted for a [fairly soft approach with reopening its baseball league](https://www.nbcnews.com/news/us-news/professional-baseball-back-taiwan-where-robots-will-be-spectators-n1180561), as has [South Korea](https://sports.yahoo.com/report-espn-reaches-agreement-with-korean-baseball-organization-to-broadcast-a-game-a-day-144941025.html), but they can arguably afford to do that because they have acted so aggressively and kept background cases so low.

It's all a risk-benefit continuum.

## Is there any way to get the risk of Covid-19 in pro sports that we bring back to zero?

No. The goal isn't zero risk. Every choice we are going to make in allowing people to gather again has a risk and benefit associated with it. The goal, then, is to keep the risk as low as possible, and below an acceptable level, while maximizing benefits. What is an acceptable level of risk? It's a judgement call, but I would say trust epidemiologists, infectious disease experts, and local public health officials to tell you when a particular plan reaches an acceptable level of risk based on the conditions on the ground.

## In any of these plans, what happens if a case does get through?

Leagues should be developing plans in concert with medical and public health officials for what happens if someone in their league -- a player, coach, or other support staff -- tests positive. What actions you would want to take really depend on your risk tolerance and any physical distancing procedures you've been employing. They could range from only quarantining people the player has spent a certain amount of time with (e.g. within 6′ for more than 15 minutes, the CDC definition of "close contact"), to their whole position group, to a whole team, to shutting down the entire league. I can't say what would be appropriate in any particular case, but you'd want to assume this would happen and have a plan in place.

I do agree with representatives from the NBA and NFL who have said we can't plan to suspend the entire league if one person tests positive. If that's going to be your bar, don't even bother restarting. It's going to happen. If you get 3-4 cases on a team, though, that probably indicates an outbreak and you need to shut that team down immediately for two weeks. If that happens on 2-3 teams you likely have a leaguewide issue and need to shut everything down for 2 weeks. The key is to have a plan that spells these guidelines out ahead of time, and *stick to them*. Be clear with your players and the public so they know just what to expect. You don't want to be making panicked, arbitrary decisions later.

## Are there certain sports that can come back sooner?

Individual sports are easier to bring back than team sports simply because there are fewer people involved. All the problems I've listed still exist for individual sports but become smaller in scale the fewer people you have to worry about. So sports like golf (which can be played outside with people largely abiding by social distancing), tennis (harder to social distance during matches, but at least it's outside), and mixed martial arts (MMA) might be some of the easier ones to bring back.

Team sports like baseball, basketball, football, hockey, soccer, and motorsports (I'm counting pit crews and engineers as teammates) are harder to bring back simply because there are more people involved. Epidemiologically speaking, it's easier to keep 75 people safe for a UFC fight than 250 safe for a football game because there's less of a chance an infected person slips through whatever defenses you've established. The baseline risk is just less. (Although it's worth noting UFC decided they somehow needed nearly [200 people](https://www.bloodyelbow.com/2020/5/21/21266254/ufc-covid-19-epidemiologist-infection-control-preventionist-flaws-plan-dana-white-mma-news) to pull off their fights in Jacksonville, but I don't think they cut that down to the bone at all -- their list of essential people included, for example, an Octagon Girl.)

The overall message here is basically the same as outside the sports world. The number of people you can allow to safely gather is directly related to the number of new cases occurring in the general population. So you need stricter containment of the epidemic and a slower trickle of new cases to restart MLB vs. stage a PGA tour event while maintaining the same level of risk for the participants and society at large.

Another dimension to think about is the geographic spread of the sport. Leagues or events that pull people from across a region are easier than those pulling people across a whole country, which in turn are easier than those pulling in people from around the globe. This is for two reasons. First is that you have to have infection control protocols in place that match the "hottest" area from which you're pulling participants or in which you're trying to operate. As a U.S. example, there are more cases in New York than Nevada right now. If you were pulling players from or trying to play games in New York and Nevada your infection control procedures everywhere would have to be tailored to the situation on the ground in New York. They could be laxer if you were only pulling participants from and playing games in Nevada. The same principle applies if you are pulling participants from just Taiwan versus from Taiwan, Spain, Sweden and Brazil. This is what makes the Olympics an [uncommonly dangerous proposition](https://www.reuters.com/article/us-health-coronavirus-olympics-vaccine/olympics-organisers-must-be-flexible-if-coronavirus-vaccine-not-ready-in-time-experts-say-idUSKBN2220OU), even next July.

Second is that your ability to hold events is dependent on the strictest restrictions across any areas in which you operate. For example, the English Premier League (EPL) would only be subject to UK regulations (though even operating in only one country is no guarantee your league won't be [shut down](https://www.si.com/soccer/2020/04/28/france-ligue-1-cancel-season-no-matches-august)). Formula 1, however, might only be able to hold races in certain countries -- maybe Monaco would allow it but Germany wouldn't. That adds an extra degree of complexity to any possible return.

Any travel a sport requires also adds risk and increases the difficulty of a return -- those that can be conducted at a handful of nearby locations are less dangerous than those that necessarily involve international travel such as F1.

## What about college vs. pro sports? Is one harder than another?

I would say bringing back college sports is probably harder because they take place in the context of a college that has to be operating. If students aren't back on campus could you really still have a college football season? College sports leaders seem divided on that issue.

There's one idea for college football that's popped up a couple places that I want to address directly: [holding the 2020 college football season in spring 2021](https://sports.yahoo.com/why-its-time-to-start-planning-2020-college-football-season-in-2021-222204040.html). I'm not buying it. Simply put, I don't see a lot of situations where we have on-campus college in spring 2021 but not fall 2020. In other words, there's little reason to believe our situation will look better in January 2021, when the spring semester starts, than August 2020. If there's a seasonal peak it will probably begin in October or November and continue through at least January 2021, leaving us in a worse situation at the start of spring semester than fall. Even if you were planning to start an abbreviated college football season in, say, March 2021, after a seasonal peak, the plan would still seem to hinge on having colleges with students on campus in January unless athletic directors change their opinion about holding sports without on-campus students. If there's no seasonal peak, things won't have gotten worse but they also won't have really improved.

Hopefully we will have ramped up testing to the level we need to contain Covid-19 by July or August, and any improvements after that will be icing on the cake. If not, we have bigger problems than college football. There's unlikely to be a vaccine by January 2021; the virus will still be here. *Maybe* we'll identify a better treatment between these two times, but that's entirely speculative -- it could come earlier, or not at all. For me to buy into this plan somebody would need to identify what concrete improvements they expect between August 2020 and January 2021 that would make it easier to pull off college football in the spring semester, because I don't see them.

Rather than skipping fall and then coming back in January, the more likely thing to happen to colleges would seem to be that they start fall semester on campus and then have to go home midway through if a seasonal uptick begins. If they're able to return it would be midway through spring. Just because of calendar quirks the most dangerous times don't line up cleanly with semester splits, which makes it more difficult to just move sports around.

It's also worth noting that more and more colleges are opting to move their semester calendars *up* to start in early August and [end by Thanksgiving](https://www.nytimes.com/2020/05/19/us/coronavirus-college-fall-semester.html) to both hopefully get ahead of a seasonal peak and avoid back-and-forth travel. I have my doubts that sport, especially football, could do that due to the training and logistics involved, but it's consistent with my thinking here.

## Aren't you being a little pessimistic? After all sports are already coming back in some parts of the world, right?

I think we're long on hope and somewhat short on examples so far. On the positive side we have already seen [fanless baseball return in Taiwan](https://www.nbcnews.com/news/us-news/professional-baseball-back-taiwan-where-robots-will-be-spectators-n1180561), whose public health officials are allowing gatherings of up to 500. They are reaping the rewards of what they sowed: an early and aggressive response to Covid-19 fueled in part by their experience with SARS in 2003. South Korea, another country that has been pointed to as as an exemplar of Covid-19 response, has [restarted fanless baseball and soccer and is even broadcasting 6 baseball games a week to the U.S.](https://sports.yahoo.com/report-espn-reaches-agreement-with-korean-baseball-organization-to-broadcast-a-game-a-day-144941025.html) These provide genuine reasons for optimism.

But looking at the broader context of things that have actually happened so far rather than just aspirational plans, Taiwan and South Korea so far are positive outliers.  Japan, on the other hand, initially appeared to have contained Covid-19 before [cases began to spike](https://www.dailymail.co.uk/news/article-8226153/Japan-calls-nationwide-state-emergency-recent-spike-coronavirus-cases.html), [including several cases among a single baseball team](https://www.si.com/mlb/dodgers/news/shintaro-fujinami-japanese-baseball-season-likely-delayed-by-covid-19); [while their season was initially set to restart on March 20, that was pushed back](https://bleacherreport.com/articles/2884907-japans-nippon-professional-baseball-j-league-extend-delays-because-of-covid-19) and they remain on hiatus. Their experience underscores the dangers of bringing sports back too soon. China, which initially planned to have basketball back by now, [has delayed its league until at least July](https://www.si.com/nba/2020/05/08/cba-stalled-out-what-it-means-for-the-nba) due to ongoing Covid-19 concerns. Germany [restarted the Bundesliga in mid-May](https://www.si.com/soccer/2020/05/22/bundesliga-behind-scenes-closed-doors-schalke-dortmund-germany) around a system where players live at home, abide by social distancing guidelines both there and at work, and are "regularly" tested. I have doubts about the wisdom of this plan, however -- Germany is still detecting several hundred new cases a day in a country of 83 million, and a first round of testing the first week of May revealed [at least 10 active cases in the Bundesliga](https://www.dfl.de/en/news/approximately-1700-coronavirus-tests-conducted-on-all-36-bundesliga-and-bundesliga-2-clubs-before-start-of-team-training/). One player was also suspended for ignoring social distancing guidelines at a team facility. [I'm still holding my breath](https://twitter.com/zbinney_NFLinj/status/1263821460453416964?s=20). The EPL has gotten clearance from the UK government for a [plan to finish out the season at 10 neutral sites beginning in June](https://www.si.com/soccer/2020/05/11/premier-league-return-uk-government-june-1-england-coronavirus), but some details remain to be worked out; as of May 26, players were [engaging in small group workouts](https://www.espn.com/soccer/english-premier-league/story/4096122/premier-league-restart-boost-as-clubs-vote-to-resume-training-amid-coronavirus) at training grounds. [Serie A](https://soccer.nbcsports.com/2020/04/29/report-paulo-dybala-tests-positive-four-times-for-covid-19/) (Italy) has also [returned to small group training](https://www.espn.com/soccer/italian-serie-a/story/4096835/serie-a-teams-cleared-for-group-training-ahead-of-make-or-break-may-28-vote) as that country has relaxed some restrictions. The Italian Sports Minister is expected to make a decision in late May on whether the league can resume this year, but a potential requirement to quarantine an entire team -- or even shut down the league -- for a single positive test could make completing the season, even if it can be resumed, difficult. [La Liga](https://soccer.nbcsports.com/2020/04/29/la-liga-players-to-return-to-training/) (Spain) has returned to individual practices and is hoping to restart the season in mid-June. [8 players and team personnel have tested positive](https://www.si.com/soccer/2020/05/11/la-liga-plan-resume-season-coronavirus-positive-tests-spain) out of 2,500 tests to date, but plans have not been altered; all players, coaches, and other staff involved in training are receiving daily Covid-19 tests. They appear to be pursuing something close to the ideal testing plan, so I will be very interested to see their experience. France and the Netherlands, meanwhile, have decreed that [no sporting events will be held in those countries, even without fans, until September 1](https://www.si.com/soccer/2020/04/28/france-ligue-1-cancel-season-no-matches-august), causing the cancellation of those countries' domestic soccer league seasons. So there's a lot of hope but few concrete examples of sports returning even in specific areas with better epidemic control so far.

In the U.S., progress so far is minimal. The PGA [and LPGA](https://www.lpga.com/news/2020/lpga-tour-announced-additional-changes-to-2020-schedule) are planning to begin [holding events without fans in June](https://www.espn.com/golf/story/_/id/29044830/what-know-right-now-pga-tour-return-june%3fplatform=amp), which seems [aggressive but not impossible](https://twitter.com/zbinney_NFLinj/status/1250927480229302276?s=20) given the unique nature of golf (individual, played outdoors, easy to integrate social distancing). Small gimmicky televised golf events for charity have already taken place. Dana White and UFC are[ holding 3 events in Jacksonville in early May](https://www.espn.com/mma/story/_/id/29094417/ufc-schedules-three-fight-cards-led-ufc-249-9-florida-no-fans). Their [safety plan was a decent start but even as written had substantial holes -- including insufficiently-frequent testing -- and was just not enough for the situation we face in the U.S.](https://theathletic.com/1809740/2020/05/12/ufc-jacksonville-event-operations-plan-covid-19-rules/?source=rss) There is also clear evidence that the written protocols were repeatedly violated, with in-Octagon post-fight interviews, Dana White getting close with fighters without a mask, fighters reportedly leaving the hotel to train at outside gyms, and [one fighter with a positive case](https://twitter.com/zbinney_NFLinj/status/1258973349956530176?s=20) in his family being allowed to "isolate whenever possible" in the host hotel for two days but being let out for a weigh-in and staredown hours before his test came back positive, as did tests on his two cornermen. We will have to wait and see whether those three cases and the protocol lapses in spark any more cases among UFC fighters and personnel. NASCAR is [holding 7 races beginning May 17](https://www.espn.com/racing/nascar/story/_/id/29118934/nascar-goes-green-seven-races-11-days), but their plan is [weak and reckless](https://twitter.com/zbinney_NFLinj/status/1256571439592939525?s=20) given the number of people involved. The NBA is [reopening training facilities for individual workouts](https://www.usnews.com/news/sports/articles/2020-04-25/ap-source-nba-facilities-will-begin-to-reopen-friday) in areas without stay-at-home orders. Although they have not announced any concrete plans for a return to play, they [appear to be circling around](https://www.espn.com/nba/story/_/id/29200286/how-close-nfl-ncaa-nba-nhl-mlb-restarts-bundesliga-ufc-coronavirus-delays#nba) a plan to centralized at the Disney Wide World of Sports Complex in Orlando. The NFL has [reopened team facilities in areas where that's allowed](https://www.espn.com/nba/story/_/id/29200286/how-close-nfl-ncaa-nba-nhl-mlb-restarts-bundesliga-ufc-coronavirus-delays#nfl) at max 50% capacity, with masks and physical distancing, and with the consent of state and local officials. The Premier Lacrosse League (PLL) has [announced it's going with a Biodome approach](https://www.insidelacrosse.com/article/pll-to-crown-champion-with-quarantined-fanless-tournament/56383) -- a 2-week quarantined tournament starting in late July at a location TBD. I'm very interested to see if they can pull it off. In Major League Soccer (MLS), some players have returned to individual training at team facilities in areas where it's allowed, and the league appears to be [zeroing in on beginning with a sequestered tournament](https://theathletic.com/1829962/2020/05/21/) where the entire league would be brought to Disney Wide World of Sports in Orlando. This is probably the plan closest to a true Biodome I've seen so far, with pre-travel testing and a quarantine before anyone enters the playing bubble. Some players don't sound thrilled, however. Major League Baseball (MLB) appears to be [focusing on](https://www.espn.com/nba/story/_/id/29200286/how-close-nfl-ncaa-nba-nhl-mlb-restarts-bundesliga-ufc-coronavirus-delays#soccer) [a plan where teams play in home markets and play an adjusted 80ish-game schedule where they only travel regionally](https://theathletic.com/1804433/2020/05/09/rosenthal-latest-details-on-baseballs-plan-to-return/) (within East, Central, and West divisions). Spring training would begin around June 14. While the plan is extremely detailed, the [biggest hole right now is testing frequency](https://theathletic.com/1827299/2020/05/21/infections-are-going-to-happen-experts-talk-risks-reality-of-mlbs-protocols/). The latest draft only says "multiple times per week," which could be anywhere from two (insufficient) to six (probably fine) tests per week. Hopefully they can figure out how to do daily testing; if so, this plan is probably okay. That said, I'm skeptical of a plan involving this little centralization in the U.S. for reasons I've outlined above; I wonder if MLB would be able to finish uninterrupted. The NHL is looking at [a Bio-hub plan](https://www.startribune.com/wild-interested-in-st-paul-being-nhl-hub-city-when-games-restart/570609002/) with a [24-team playoff in 2 hub cities](https://boston.cbslocal.com/2020/05/26/gary-bettman-nhl-return-to-play-plan/); they have officially scrapped the rest of their regular season.

## Could sports come back in some geographic areas (of the U.S.) sooner?

Here I'm mostly referring to youth and amateur sports, as pro sports either have to operate nationally or will centralize in a few areas where things are under control.

Anyway, yes and no. I'm of two minds on this.

There's no question that we don't have one Covid-19 epidemic in the U.S. right now. We have a whole bunch of epidemics at different stages. Washington and California acted early and largely tamped down their epidemics before they got out of control. New York got out of control but is currently seeing hospitalizations dropping, which is an encouraging sign. Other areas of the country, particularly in the south and Midwest, are still thought to be on the upswing.

I also think different levels of social distancing and shelter-in-place orders are necessary for different areas of the U.S. We are unlikely to fully stamp out Covid-19, but if we do things right you will hopefully in the coming months see more localized outbreaks that are quickly contained. So it's quite possible you could have some areas that have less strict business closures and allow larger gatherings than others, including those of a size that would allow fanless sports to return -- as is already happening in Taiwan, for example, thanks to their uncommonly early and aggressive action. Political differences will surely play a role here, too, but I'm just speaking from a public health perspective.

*However,* a virus does not obey county, city, or state borders. (National borders may be slightly harder for it to cross depending on their porousness and travel restrictions.) A virus's sole purpose, insofar as it can have one, is to invade your cells to make copies of itself at the fastest rate it can without killing you (but sometimes it does anyway). So if one area of the country is irresponsible in allowing sports back when it shouldn't, all of us will suffer if the virus then spreads. We all need to be pulling together in this.

The reason we needed strict nationwide measures initially is because, due to a slow response and lack of testing, we didn't have a clear idea where the virus was and wasn't. We lost it in the damn lights. We're getting better about knowing who's sick where, but we still don't have testing where it needs to be nor have we actually acted harshly enough to reduce the number of cases in most areas. In football terms: playing defense 11-on-11 is hard enough, but we basically let the virus sneak 4 extra WRs onto the field. I don't care how good your defense is, you can't stop 9 receivers. So we had to beg the refs to blow the whistle and stop the game until we can get the extra receivers off the field. We're currently trying to usher them back to the sideline, with mixed success. That's the situation we're in right now with trying to both flatten the curve and get to the other side where the number of new cases slows substantially.

That's why we still need fairly broad-based draconian social distancing measures, because they're the *only* tool we have to stop the spread at its current stage. If we can get testing ramped up further and beat the current wave back to a manageable number of new infections hopefully our local and state public health departments -- with a *huge* infusion of funding and public cooperation -- can keep an eye on things and we can switch to a more proactive and targeted approach that allows us to institute more restrictive measures only in areas where virus activity is more widespread. But I'm increasingly pessimistic about reaching this point. Our prevailing national plan right now seems to be "eh, good enough" because not enough people have died yet. We can't plan to save our lives.

I suppose my overall message is, yes, we're in a situation where having sports is "more OK" in some parts of the U.S. than others. But for this to not cause a new wave of infections every single jurisdiction has to be extremely responsible about what they're allowing and coordinate with their neighbors to keep infections from spilling over. I'll leave it to you as to whether you want to bet on that.

## These are young, elite athletes we're talking about here. Is there really that much risk here from Covid-19? Why can't they just play?

First of all, professional sports doesn't just involve athletes. It involves coaches and officials/referees/umpires, for example -- they're not all young healthy folks. You would also need medical personnel, athletic trainers, some sort of broadcast staff like camera operators, security, and other critical gameday and team facility staff. So you have to think about the risks to all these people, which are likely much higher.

There are also the [non-fatal long-term outcomes of Covid-19](https://www.vox.com/2020/5/8/21251899/coronavirus-long-term-effects-symptoms) to consider. Even if someone doesn't die it's possible they'll suffer lingering lung or other organ damage from the disease. These could be career-threatening for some athletes. This is something scientists are still studying since the disease has only been around for a few months, but it's a possibility worth considering.

Even if 99.9% of young athletes who get the virus will recover fully with no lasting repercussions, think of it this way. I walk you down to the sideline of a football field and tell you you have to sprint straight across it from one sideline to the other. You can start anywhere you want between the goal lines, but a 3-inch strip is covered in land mines that could kill or maim you. How much would I have to pay you to make that run?

## OK but what if we just rip the Band-Aid off, "reopen" everything and let sports come back? How bad could it be?

If we just decide to let it burn in most areas it'd probably be over by the fall or so. You'd have sports back. You'd also have 1-2 million dead people. Let's take [1.7 million](https://nymag.com/intelligencer/2020/03/cdcs-worst-case-coronavirus-model-210m-infected-1-7m-dead.html) U.S. deaths, the upper end of initial CDC estimates but somewhat below the [Imperial College London model's initial 2.2 million death estimate](https://www.nytimes.com/2020/03/17/world/europe/coronavirus-imperial-college-johnson.html) absent any social distancing.

Let's talk about that number. We're really bad at dealing with big numbers. That is a Super Bowl blown up by terrorists, killing every single person in the building...24 times. It's 9/11 every day...for 18 months. What freedoms have we given up, what wars have we fought, what blood have we shed, what money have we spent in the interest of stopping one more 9/11? This is 9/11 every day for 18 months.

So no, I would prefer it if we didn't do that.

## Why are we even talking about bringing pro sports back? Isn't that a little ridiculous at this stage?

I'd argue no! It's trite, but sports is a microcosm of society and often reflects the best of us. For sports fans like me and many others it can also be a powerful psychological boon that shows us we're on the long, slow road back to normality. I think there's a real argument to be made for bringing televised sports back as soon as possible as long as public health and player and staff safety is kept paramount. The benefits could outweigh the risks.

The argument for having fans in the stands is weaker. What's really the additional benefit there, other than financial for some leagues? There's some, sure, but I'd wager it's less than getting televised sports back. And you would have to take on a *lot* of risk to get that minimal benefit. It's not worth it in my mind.

## How quickly can sports come back once conditions on the ground merit that?

Good question. It won't be immediate. Many athletes have found it a lot harder to train while quarantined or under shelter-in-place orders, for example. They need time to spin back up to full speed. For football, for example, taking guys straight out of shelter-in-place and putting them right on the field would probably result in both a bad product and a high risk of injuries. The necessary training and ramp-up periods will vary by sport, and I trust the athletic trainers and medical personnel in those leagues to make those calls. The point is, we can't OK a plan one day and have games start the next. Players in virtually any sport will need time to get back in game shape.

That time might be extended if that training has to be accomplished after they enter a Biodome or other protected virus-free zone, too.

## What can teams and leagues be doing right now to prepare?

They could hire epidemiologists like me and my colleagues in infectious disease to help them craft realistic plans that get sports back as quickly as possible while protecting public health. I hope every league has already done this, frankly.

They could also potentially start "wargaming" or simulating the risks from different approaches (e.g. Biodome vs. softer sequestering approach) under a range of reasonable assumptions for how quickly the infection spreads (commonly called the reproductive number R_0), current prevalence and incidence and immunity numbers (basically, where we are on the "curve"), and so forth. Every league has a bunch of quantitative analysts; hook 'em up with infectious disease modelers and use 'em.

Leagues should also be developing specific plans in concert with medical and public health officials for what happens when someone in their league -- a player, coach, or other support staff -- tests positive. Would you just isolate them and quarantine anyone with whom they've had close contact? Quarantine their whole position group? The whole team (what would that mean for scheduling)? The whole league? What if there are 2-3 cases on different teams?

Teams should also be considering creative plans to limit the potential damage from a single positive test, such as practicing in consistent groups to create smaller "networks" within a team that can be separately quarantined if anyone in that network gets infected. Splitting your best players across these networks would further help limit damage but must be balanced against the downsides of disrupting team chemistry and practice schemes.

## What about youth leagues who can't afford to do all this? Is there anything they can do to make themselves safer?

Leagues and teams at any level -- pro, college, and youth -- should be thinking about lower-cost hygiene and physical distancing protocols they can implement to reduce the spread of any infections that appear among their athletes, coaches, or support staff.

On the hygiene front there should be easily-accessible hand washing and sanitizer stations, and all equipment should be thoroughly disinfected between practices and games -- and perhaps even within games, such as wiping baseballs down every half-inning and delivering them with gloved ballboys to gloved umpires.

On the physical distancing front, any steps you can take to [reduce the number of people gathering in close proximity will help](https://www.nytimes.com/2020/04/28/sports/fauci-sports-reopening-pandemic.html?auth=login-google&smid=tw-nytsports&smtyp=cur). If you have fans for youth sports, maybe restrict them to a small number of immediate family or friends per player, remind them to sit and stand apart and don't intermingle, and discourage the elderly and higher-risk from attending. As noted above, practice in separate sub-groups if possible. Limit time in cramped locker rooms (e.g. give speeches outside) or only allow players in there in shifts. Physical distancing during play is obviously easier in some sports than others but even in those that require close contact you could take steps to reduce risks, such as installing clear face shields in all football helmets.

You could also leverage existing networks: youth leagues could be organized within schools or neighborhoods, for example, so any infection only spreads through that single network rather than both the school/neighborhood and a separate youth sports network. Get creative!

[Travel leagues and large tournaments](https://www.nytimes.com/2020/05/12/sports/baseball/coronavirus-youth-baseball-tournament-missouri.html) increase risks substantially, and the situation would have to improve *dramatically* nationwide for me to be comfortable with those returning. Don't hold them, and don't let you kids do them. Please.

Here's an [outstanding article](https://www.aspenprojectplay.org/coronavirus-and-youth-sports/reports/2020/4/30/how-will-youth-sports-return-to-play-usopc-offers-first-glimpse) and [information clearinghouse](https://www.aspenprojectplay.org/coronavirus-and-youth-sports) summarizing the current state of youth sports and a host of guidelines from many institutions offering concrete advice on when and how to return.

## Is there anything that could change your opinion?

Of course. There are still many things we don't know, and the heart of science is being willing to adjust your thoughts to new data. The biggest unknown is what the number of active cases is going to look like in the U.S. moving forward this summer. Will we eventually see a sustained decline thanks in part to warmer weather? Will we stall out at our current plateau of 20-30,000 cases per day? Will relaxation of social distancing measures occur too quickly and recklessly, leading to a spike in cases?

And what will happen with testing? Will we get to the million or so tests a day many experts say we need to safely reopen? Will saliva-based testing expand? If these do happen, when?

Developments on these and other issues, such as treatments (and obviously vaccines) may cause my opinions to shift. Some people take this as a sign of weakness or an admission that I was "wrong," but getting incrementally less-wrong over time as more data comes in is the core of science. Unshakable strength of your convictions is not actual strength. Don't ding me for critical thinking, that's all I ask.
